In [4]:
# numpy
# How to import NumPy
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
a[0]=10 # array is mutable
a

array([10,  2,  3,  4,  5,  6])

In [6]:
a[:3]

array([10,  2,  3])

In [5]:
# Single dimension array 
'''
arr = np.array([1, 2, 3])
print(arr)

'''
# two dimension array
'''
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

'''
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("array from a tuple:",arr)


array from a tuple: [1 3 2]


In [7]:
# accessing array elements 

arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])
print("second row last element:",arr1[1,2])

second row last element: 6


In [11]:
# slicing

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [12]:
# Array attributes - ndim, shape, size, and dtype attributes of an array

# ndim - number of dimensions of an array
print(arr.ndim)
# shape - a tuple with number of elements and dimension
arr.shape



2


(4, 4)

In [18]:
# size

arr.size

16

In [19]:
# datatype
arr.dtype

dtype('float64')

In [23]:
# create a basic array - np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

#np.zeros(2)

#np.zeros(2,dtype=int)

np.ones(2)

array([1., 1.])

In [23]:
# array with a range
np.arange(4)

# Create Array of Integers 30 to 70
# Create Array of Even Integers 30 to 70

array([0, 1, 2, 3])

In [ ]:
# Create Array of Zeros, Ones, Fives
# np.flipud(array) - reverse
# np.dot( ) - multiplication

# sort the given array - (np.sort(arr,axis=None)) -- axis=0,axis=1

In [24]:
# array with evenly specified range
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [25]:
# generate a sequence of evenly spaced numbers - linspace()
# np.linspace(start, stop, num=50) 
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [26]:
np.linspace(1, 5, 3)

array([1., 3., 5.])

In [27]:
a, step = np.linspace(0, 1, 5, retstep=True)
print(a)     
print(step)  

[0.   0.25 0.5  0.75 1.  ]
0.25


In [28]:
np.linspace(0, 1, 5, endpoint=False) # do not want to include stop value

array([0. , 0.2, 0.4, 0.6, 0.8])

In [29]:
# itemsize - The number of bytes used to store each individual element in the array.

a = np.array([1, 2, 3])
print(a.dtype)      
print(a.itemsize) 

int64
8


In [30]:
# indexing in single and multidimensional arrays

a = np.array([10, 20, 30, 40, 50])
print(a[0])  
print(a[2]) 

10
30


In [31]:
# negative indexing
print(a[-1])  
print(a[-2])  

50
40


In [32]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b[0, 0])  
print(b[1, 2])  
print(b[-1, -1])  

1
6
9


In [33]:
# array slicing should be called as advanced indexing

a = np.array([10, 20, 30, 40, 50])

print(a[1:4])    
print(a[:3])     
print(a[::2])    
print(a[::-1])   

[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [4]:
import numpy as np

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

#print(b[0:2, :]) 
#print(b[:, 1:3]) 
#print(b[[0, 2], :])
#print()
print(b[[0, 2], :][:, [0, 2]])
print()
print(b[:, [0, 2]])


[[1 3]
 [7 9]]

[[1 3]
 [4 6]
 [7 9]]


In [ ]:
# practice programs

# Create a 3×3 matrix with values from 1 to 10. 
# Create a 4×4 matrix filled with zeros.
# Create a 3×2 matrix of ones.
# Add two matrices.
# Multiply two matrices.
# Reshape a 1D array of size 12 into a 3×4 matrix.
# Find the transpose of a matrix.
# Flatten a 2D matrix to 1D.


In [17]:
# vstack, hstack and concatenation (works like hstack)
# In vstack columns should match (axis=0) - number of cols should be same
# In hstack rows should match (axis=1) - number of rows should be same

a = np.array([[1, 2], [3, 4]])
b = np.array([[5,6]])

result = np.vstack((a, b)) # row where axis=0
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [24]:
# hstack rows should match
a = np.array([[1, 2], [3, 4]])
b = np.array([[5],[6]])


result = np.hstack((a, b)) # column where axis=1
print(result)


[[1 2 5]
 [3 4 6]]


In [ ]:
# concatenate

np.concatenate((a,b),axis=0/1)

In [22]:
rand_arr = np.random.randint(1, 10, size=(3,3))  # random integers 1-9
print("Random 3x3 array:\n", rand_arr)

rand_float = np.random.rand(2,3)  # random floats between 0 and 1
print("Random floats 2x3:\n", rand_float)


Random 3x3 array:
 [[7 1 9]
 [8 3 2]
 [6 3 3]]
Random floats 2x3:
 [[0.77138655 0.44883244 0.59278086]
 [0.60150446 0.79014767 0.43483704]]
