## 1. Basic Array Creation and Manipulation

In [1]:
# Import NumPy library
import numpy as np

In [2]:
# Create a basic array and modify elements
a = np.array([1, 2, 3, 4, 5, 6])
a[0] = 10  # Arrays are mutable
print("Modified array:", a)

# Array slicing
print("First 3 elements:", a[:3])

Modified array: [10  2  3  4  5  6]
First 3 elements: [10  2  3]


In [3]:
# Single dimension array
arr_1d = np.array([1, 2, 3])
print("1D array:", arr_1d)

# Two dimension array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D array:\n", arr_2d)

# Creating an array from tuple
arr_from_tuple = np.array((1, 3, 2))
print("Array from tuple:", arr_from_tuple)

1D array: [1 2 3]
2D array:
 [[1 2 3]
 [4 5 6]]
Array from tuple: [1 3 2]


## 2. Accessing and Indexing Arrays

In [4]:
# Accessing 2D array elements
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("Second row, last element:", arr1[1, 2])

Second row, last element: 6


In [5]:
# Advanced slicing on 2D arrays
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Get first 2 rows and alternate columns (0 and 2)
arr2 = arr[:2, ::2]
print("First 2 rows and alternate columns:\n", arr2)

First 2 rows and alternate columns:
 [[-1.  0.]
 [ 4.  6.]]


In [6]:
# Indexing in single dimensional arrays
a = np.array([10, 20, 30, 40, 50])
print("First element:", a[0])
print("Third element:", a[2])

# Negative indexing
print("Last element:", a[-1])
print("Second last element:", a[-2])

First element: 10
Third element: 30
Last element: 50
Second last element: 40


In [7]:
# Indexing in multidimensional arrays
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Element at [0,0]:", b[0, 0])
print("Element at [1,2]:", b[1, 2])
print("Element at [-1,-1]:", b[-1, -1])

Element at [0,0]: 1
Element at [1,2]: 6
Element at [-1,-1]: 9


In [8]:
# Array slicing (advanced indexing)
a = np.array([10, 20, 30, 40, 50])

print("Elements from index 1 to 3:", a[1:4])
print("First 3 elements:", a[:3])
print("Every alternate element:", a[::2])
print("Reversed array:", a[::-1])

Elements from index 1 to 3: [20 30 40]
First 3 elements: [10 20 30]
Every alternate element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [9]:
# Fancy indexing with 2D arrays
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Select specific rows and columns
print("Rows 0 and 2, columns 0 and 2:\n", b[[0, 2], :][:, [0, 2]])
print("\nAll rows, columns 0 and 2:\n", b[:, [0, 2]])

Rows 0 and 2, columns 0 and 2:
 [[1 3]
 [7 9]]

All rows, columns 0 and 2:
 [[1 3]
 [4 6]
 [7 9]]


## 3. Array Attributes

In [10]:
# Array attributes: ndim, shape, size, and dtype
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Number of dimensions
print("Number of dimensions:", arr.ndim)

# Shape (rows, columns)
print("Shape:", arr.shape)

# Total number of elements
print("Size:", arr.size)

# Data type of elements
print("Data type:", arr.dtype)

Number of dimensions: 2
Shape: (4, 4)
Size: 16
Data type: float64


In [11]:
# itemsize - bytes per element
a = np.array([1, 2, 3])
print("Data type:", a.dtype)
print("Bytes per element:", a.itemsize)

Data type: int64
Bytes per element: 8


## 4. Creating Arrays with Built-in Functions

In [12]:
# Create arrays of zeros and ones
zeros_arr = np.zeros(2)
print("Zeros array:", zeros_arr)

zeros_int = np.zeros(2, dtype=int)
print("Zeros array (int):", zeros_int)

ones_arr = np.ones(2)
print("Ones array:", ones_arr)

Zeros array: [0. 0.]
Zeros array (int): [0 0]
Ones array: [1. 1.]


In [13]:
# Create array with range
range_arr = np.arange(4)
print("Range 0-3:", range_arr)

# Create array of integers 30 to 70
int_arr = np.arange(30, 71)
print("Integers 30-70:", int_arr)

# Create array of even integers 30 to 70
even_arr = np.arange(30, 71, 2)
print("Even integers 30-70:", even_arr)

Range 0-3: [0 1 2 3]
Integers 30-70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
Even integers 30-70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [14]:
# Array with evenly spaced range and step
stepped_arr = np.arange(2, 9, 2)
print("Array with step 2:", stepped_arr)

Array with step 2: [2 4 6 8]


In [15]:
# Generate evenly spaced numbers using linspace
# np.linspace(start, stop, num=50)
a = np.linspace(0, 1, 5)
print("5 values from 0 to 1:", a)

b = np.linspace(1, 5, 3)
print("3 values from 1 to 5:", b)

5 values from 0 to 1: [0.   0.25 0.5  0.75 1.  ]
3 values from 1 to 5: [1. 3. 5.]


In [16]:
# Get step size with linspace
a, step = np.linspace(0, 1, 5, retstep=True)
print("Array:", a)
print("Step size:", step)

Array: [0.   0.25 0.5  0.75 1.  ]
Step size: 0.25


In [17]:
# Linspace without endpoint
no_endpoint = np.linspace(0, 1, 5, endpoint=False)
print("Without endpoint:", no_endpoint)

Without endpoint: [0.  0.2 0.4 0.6 0.8]


## 5. Array Stacking and Concatenation

In [18]:
# Vertical stacking (vstack) - stacks arrays row-wise
# Number of columns should match (axis=0)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.vstack((a, b))
print("Vertical stack:\n", result)

Vertical stack:
 [[1 2]
 [3 4]
 [5 6]]


In [19]:
# Horizontal stacking (hstack) - stacks arrays column-wise
# Number of rows should match (axis=1)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])

result = np.hstack((a, b))
print("Horizontal stack:\n", result)

Horizontal stack:
 [[1 2 5]
 [3 4 6]]


In [20]:
# Concatenate arrays along specified axis
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenate along axis 0 (like vstack)
result_axis0 = np.concatenate((a, b), axis=0)
print("Concatenate axis=0:\n", result_axis0)

Concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]]


## 6. Array Reshaping and Flattening

In [21]:
# Reshape arrays
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(f"Original 1D array: {arr_1d}, Shape: {arr_1d.shape}")

# Reshape with -1 to automatically infer dimension
arr_inferred = arr_1d.reshape(3, -1)  # Automatically infers 2 columns
print(f"Reshaped to 3x2:\n{arr_inferred}, Shape: {arr_inferred.shape}")

Original 1D array: [1 2 3 4 5 6], Shape: (6,)
Reshaped to 3x2:
[[1 2]
 [3 4]
 [5 6]], Shape: (3, 2)


In [22]:
# Reshape with automatic row inference
arr_1d = np.arange(6)  # [0, 1, 2, 3, 4, 5]
arr_reshaped = arr_1d.reshape(-1, 3)  # Automatically infer number of rows
print("Auto reshape to ?x3:\n", arr_reshaped)

Auto reshape to ?x3:
 [[0 1 2]
 [3 4 5]]


In [23]:
# Flatten a 2D array to 1D
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print("Flattened array:", flattened_arr)

# Alternative: ravel() - returns a view when possible
raveled_arr = arr.ravel()
print("Raveled array:", raveled_arr)

Flattened array: [1 2 3 4 5 6]
Raveled array: [1 2 3 4 5 6]


## 7. Random Arrays

In [24]:
# Generate random arrays
rand_arr = np.random.randint(1, 10, size=(3, 3))  # Random integers 1-9
print("Random 3x3 array:\n", rand_arr)

rand_float = np.random.rand(2, 3)  # Random floats between 0 and 1
print("Random floats 2x3:\n", rand_float)

Random 3x3 array:
 [[8 9 4]
 [2 8 4]
 [2 2 9]]
Random floats 2x3:
 [[0.46992909 0.35969084 0.2562986 ]
 [0.20618748 0.20196399 0.82138777]]


## 8. Python List Comprehensions (Bonus)

In [25]:
# List comprehension - Pythonic way to create lists
numbers = [1, 2, 3, 4, 5]
squares = [x**2 for x in numbers]
print("Squares:", squares)

# Using range
squares_range = [x**2 for x in range(5)]
print("Squares from range:", squares_range)

# With condition
evens = [x for x in range(5) if x % 2 == 0]
print("Even numbers:", evens)

Squares: [1, 4, 9, 16, 25]
Squares from range: [0, 1, 4, 9, 16]
Even numbers: [0, 2, 4]


## 9. Practice Exercises - Solved

In [26]:
# Exercise 1: Create a 3x3 matrix with values from 1 to 9
import numpy as np
matrix = np.arange(1, 10).reshape((3, 3))
print("3x3 matrix with values 1-9:\n", matrix)

3x3 matrix with values 1-9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
# Exercise 2: Create a 4x4 matrix filled with zeros
matrix = np.zeros((4, 4), dtype=int)
print("4x4 zero matrix:\n", matrix)

4x4 zero matrix:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [28]:
# Exercise 3: Create a 3x2 matrix of ones
matrix = np.ones((3, 2), dtype=int)
print("3x2 ones matrix:\n", matrix)

3x2 ones matrix:
 [[1 1]
 [1 1]
 [1 1]]


In [29]:
# Exercise 4: Add two matrices (element-wise addition)
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = matrix1 + matrix2
print("Matrix addition:\n", result)

Matrix addition:
 [[ 6  8]
 [10 12]]


In [30]:
# Exercise 5: Multiply two matrices
# Element-wise multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_elementwise = matrix1 * matrix2
print("Element-wise multiplication:\n", result_elementwise)

# Matrix multiplication using np.dot()
result_dot = np.dot(matrix1, matrix2)
print("\nMatrix multiplication (dot product):\n", result_dot)

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Matrix multiplication (dot product):
 [[19 22]
 [43 50]]


In [31]:
# Exercise 6: Reshape a 1D array of size 12 into a 3x4 matrix
array = np.arange(12)
matrix = array.reshape((3, 4))
print("1D array:", array)
print("\nReshaped to 3x4:\n", matrix)

1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
# Exercise 7: Find transpose of a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original matrix:\n", matrix)

# Method 1: Using .T attribute
transpose_matrix = matrix.T
print("\nTranspose (using .T):\n", transpose_matrix)

# Method 2: Using np.transpose()
transpose_matrix2 = np.transpose(matrix)
print("\nTranspose (using np.transpose()):\n", transpose_matrix2)

Original matrix:
 [[1 2 3]
 [4 5 6]]

Transpose (using .T):
 [[1 4]
 [2 5]
 [3 6]]

Transpose (using np.transpose()):
 [[1 4]
 [2 5]
 [3 6]]


In [33]:
# Exercise 8: Flatten a 2D matrix to 1D
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D matrix:\n", matrix)

# Method 1: Using flatten()
flattened = matrix.flatten()
print("\nFlattened array:", flattened)

# Method 2: Using ravel()
raveled = matrix.ravel()
print("Raveled array:", raveled)

Original 2D matrix:
 [[1 2 3]
 [4 5 6]]

Flattened array: [1 2 3 4 5 6]
Raveled array: [1 2 3 4 5 6]


In [34]:
# Exercise 9: Sort an array
arr = np.array([[3, 1, 2], [6, 4, 5]])
print("Original array:\n", arr)

# Sort along axis=None (flatten and sort)
sorted_flat = np.sort(arr, axis=None)
print("\nSorted (flattened):", sorted_flat)

# Sort along axis=0 (sort each column)
sorted_axis0 = np.sort(arr, axis=0)
print("\nSorted along axis=0 (columns):\n", sorted_axis0)

# Sort along axis=1 (sort each row)
sorted_axis1 = np.sort(arr, axis=1)
print("\nSorted along axis=1 (rows):\n", sorted_axis1)

Original array:
 [[3 1 2]
 [6 4 5]]

Sorted (flattened): [1 2 3 4 5 6]

Sorted along axis=0 (columns):
 [[3 1 2]
 [6 4 5]]

Sorted along axis=1 (rows):
 [[1 2 3]
 [4 5 6]]


In [35]:
# Exercise 10: Reverse an array using np.flipud()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)

# Flip upside down (reverse rows)
flipped = np.flipud(arr)
print("\nFlipped upside down:\n", flipped)

# Flip left-right (reverse columns)
flipped_lr = np.fliplr(arr)
print("\nFlipped left-right:\n", flipped_lr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped upside down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

Flipped left-right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [36]:
# Exercise 11: Create an array of fives using np.full()
# Create a 3x3 array filled with 5s
fives_array = np.full((3, 3), 5)
print("3x3 array of fives:\n", fives_array)

# Alternative: using np.ones() and multiplication
fives_alt = np.ones((3, 3), dtype=int) * 5
print("\nAlternative method:\n", fives_alt)

3x3 array of fives:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Alternative method:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


## 10. Additional Practice Problems - Solved

In [37]:
# Create array of integers 30 to 70
arr_30_70 = np.arange(30, 71)
print("Integers from 30 to 70:")
print(arr_30_70)

Integers from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [38]:
# Create array of even integers 30 to 70
even_30_70 = np.arange(30, 71, 2)
print("Even integers from 30 to 70:")
print(even_30_70)

Even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [39]:
# Create arrays of zeros, ones, and fives
# 2x3 array of zeros
zeros = np.zeros((2, 3), dtype=int)
print("2x3 array of zeros:\n", zeros)

# 2x3 array of ones
ones = np.ones((2, 3), dtype=int)
print("\n2x3 array of ones:\n", ones)

# 2x3 array of fives
fives = np.full((2, 3), 5)
print("\n2x3 array of fives:\n", fives)

2x3 array of zeros:
 [[0 0 0]
 [0 0 0]]

2x3 array of ones:
 [[1 1 1]
 [1 1 1]]

2x3 array of fives:
 [[5 5 5]
 [5 5 5]]


In [40]:
# Matrix multiplication using np.dot()
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6]])
matrix_b = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Dot product (matrix multiplication)
result = np.dot(matrix_a, matrix_b)
print("Matrix A (2x3):\n", matrix_a)
print("\nMatrix B (3x2):\n", matrix_b)
print("\nDot product A·B (2x2):\n", result)

# Alternative using @ operator (Python 3.5+)
result_alt = matrix_a @ matrix_b
print("\nUsing @ operator:\n", result_alt)

Matrix A (2x3):
 [[1 2 3]
 [4 5 6]]

Matrix B (3x2):
 [[ 7  8]
 [ 9 10]
 [11 12]]

Dot product A·B (2x2):
 [[ 58  64]
 [139 154]]

Using @ operator:
 [[ 58  64]
 [139 154]]


In [41]:
# Create empty array using np.empty()
# Note: empty() creates an array with uninitialized values (whatever was in memory)
empty_arr = np.empty((2, 3))
print("Empty array (uninitialized values):\n", empty_arr)

# It's usually better to use zeros() or ones() for predictable values
zeros_arr = np.zeros((2, 3))
print("\nZeros array (initialized to 0):\n", zeros_arr)

Empty array (uninitialized values):
 [[3.29344e-319 0.00000e+000 0.00000e+000]
 [0.00000e+000 0.00000e+000 0.00000e+000]]

Zeros array (initialized to 0):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
# Identity matrix
identity_3x3 = np.eye(3)
print("3x3 Identity matrix:\n", identity_3x3)

# Identity matrix with different dimensions
identity_3x4 = np.eye(3, 4)
print("\n3x4 Identity matrix:\n", identity_3x4)

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x4 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [43]:
# Diagonal matrix
diagonal = np.diag([1, 2, 3, 4])
print("Diagonal matrix:\n", diagonal)

# Extract diagonal from a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
diag_elements = np.diag(matrix)
print("\nOriginal matrix:\n", matrix)
print("\nDiagonal elements:", diag_elements)

Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements: [1 5 9]


In [44]:
# Array arithmetic operations
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array a:", a)
print("Array b:", b)
print("\nAddition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (a / b):", a / b)
print("Power (a ** 2):", a ** 2)
print("Square root:", np.sqrt(a))

Array a: [10 20 30 40]
Array b: [1 2 3 4]

Addition (a + b): [11 22 33 44]
Subtraction (a - b): [ 9 18 27 36]
Multiplication (a * b): [ 10  40  90 160]
Division (a / b): [10. 10. 10. 10.]
Power (a ** 2): [ 100  400  900 1600]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532]


In [45]:
# Statistical operations
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Array:\n", arr)
print("\nSum of all elements:", np.sum(arr))
print("Sum along axis=0 (columns):", np.sum(arr, axis=0))
print("Sum along axis=1 (rows):", np.sum(arr, axis=1))
print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))
print("Minimum value:", np.min(arr))
print("Maximum value:", np.max(arr))
print("Index of minimum:", np.argmin(arr))
print("Index of maximum:", np.argmax(arr))

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sum of all elements: 78
Sum along axis=0 (columns): [15 18 21 24]
Sum along axis=1 (rows): [10 26 42]

Mean: 6.5
Median: 6.5
Standard deviation: 3.452052529534663
Minimum value: 1
Maximum value: 12
Index of minimum: 0
Index of maximum: 11


In [46]:
# Boolean indexing and filtering
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Filter values greater than 5
filtered = arr[arr > 5]
print("\nValues > 5:", filtered)

# Filter even numbers
evens = arr[arr % 2 == 0]
print("Even numbers:", evens)

# Multiple conditions
between = arr[(arr > 3) & (arr < 8)]
print("Values between 3 and 8:", between)

Original array: [ 1  2  3  4  5  6  7  8  9 10]

Values > 5: [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]
Values between 3 and 8: [4 5 6 7]


In [47]:
# Array copying - important difference between view and copy
original = np.array([1, 2, 3, 4, 5])
print("Original array:", original)

# View (changes affect original)
view = original.view()
view[0] = 999
print("\nAfter modifying view:")
print("View:", view)
print("Original:", original)  # Original is also changed!

# Copy (independent)
original = np.array([1, 2, 3, 4, 5])
copy = original.copy()
copy[0] = 888
print("\nAfter modifying copy:")
print("Copy:", copy)
print("Original:", original)  # Original unchanged

Original array: [1 2 3 4 5]

After modifying view:
View: [999   2   3   4   5]
Original: [999   2   3   4   5]

After modifying copy:
Copy: [888   2   3   4   5]
Original: [1 2 3 4 5]


In [48]:
# Broadcasting - operations on arrays of different shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print("Array a (2x3):\n", a)
print("\nArray b (1x3):", b)
print("\nBroadcasting a + b:\n", a + b)
print("\nBroadcasting a * b:\n", a * b)

Array a (2x3):
 [[1 2 3]
 [4 5 6]]

Array b (1x3): [10 20 30]

Broadcasting a + b:
 [[11 22 33]
 [14 25 36]]

Broadcasting a * b:
 [[ 10  40  90]
 [ 40 100 180]]
